# site
title: Äggie Lee Pak Yee
url: "https://itchyeggie.github.io"
baseurl: "/doodlin-archive" 
favicon: "/doodlin-archive/assets/ico.png"

# bio
header: Äggie Lee Pak Yee
desc: >
      李 柏 誼 's doodlin' archive

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
