# site
title: Äggie Pak Yee Lee
url: "https://itchyeggie.github.io"
baseurl: "/doodlin-archive" 

# bio
header: Äggie Pak Yee Lee
desc: >
      李 柏 誼 's doodlin' archive

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
